party_name = "test"
[[pokemon]]
id = 9
name = "blastoise"
moves = [ 270, 25, 38, 57,]
nature = 18
ability = 44

[pokemon.evs]
hp = 0
attack = 0
defense = 0
sp_attack = 32
sp_defense = 32
speed = 2

[[pokemon]]
id = 9
name = "blastoise"
moves = [ 8, 270, 38, 57,]
nature = 25
ability = 44

[pokemon.evs]
hp = 0
attack = 0
defense = 0
sp_attack = 32
sp_defense = 32
speed = 2