party_name = "0"
[[pokemon]]
pokemon_id = 0
name = "（未選択）"
level = 50
nature_id = 1
nature_name = "Hardy"
ability_id = 0
ability_name = "（未選択）"
moves = [ 0, 0, 0, 0,]

[pokemon.evs]
hp = 0
attack = 0
defense = 0
special_attack = 0
special_defense = 0
speed = 0
[[pokemon]]
pokemon_id = 0
name = "（未選択）"
level = 50
nature_id = 1
nature_name = "Hardy"
ability_id = 0
ability_name = "（未選択）"
moves = [ 0, 0, 0, 0,]

[pokemon.evs]
hp = 0
attack = 0
defense = 0
special_attack = 0
special_defense = 0
speed = 0
[[pokemon]]
pokemon_id = 0
name = "（未選択）"
level = 50
nature_id = 1
nature_name = "Hardy"
ability_id = 0
ability_name = "（未選択）"
moves = [ 0, 0, 0, 0,]

[pokemon.evs]
hp = 0
attack = 0
defense = 0
special_attack = 0
special_defense = 0
speed = 0
[[pokemon]]
pokemon_id = 0
name = "（未選択）"
level = 50
nature_id = 1
nature_name = "Hardy"
ability_id = 0
ability_name = "（未選択）"
moves = [ 0, 0, 0, 0,]

[pokemon.evs]
hp = 0
attack = 0
defense = 0
special_attack = 0
special_defense = 0
speed = 0
[[pokemon]]
pokemon_id = 0
name = "（未選択）"
level = 50
nature_id = 1
nature_name = "Hardy"
ability_id = 0
ability_name = "（未選択）"
moves = [ 0, 0, 0, 0,]

[pokemon.evs]
hp = 0
attack = 0
defense = 0
special_attack = 0
special_defense = 0
speed = 0
[[pokemon]]
pokemon_id = 0
name = "（未選択）"
level = 50
nature_id = 1
nature_name = "Hardy"
ability_id = 0
ability_name = "（未選択）"
moves = [ 0, 0, 0, 0,]

[pokemon.evs]
hp = 0
attack = 0
defense = 0
special_attack = 0
special_defense = 0
speed = 0
